name: subsystems
description: A sample command-line application.
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  burt_network: ^2.3.1
  collection: ^1.19.0
  csv: ^6.0.0
  ffi: ^2.1.3
  libserialport: ^0.3.0+1
  meta: ^1.14.0
  osc: ^1.0.0
  protobuf: ^3.1.0

dev_dependencies:
  ffigen: ^16.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
