name: subsystems
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  burt_network: 
    git: https://github.com/BinghamtonRover/Dart-Networking.git
  ffi: ^2.0.2

dev_dependencies:
  ffigen: ^9.0.1
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
